// <auto-generated />
using System;
using JAP_TASK_1_WEB_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JAP_TASK_1_WEB_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210903122453_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CastMemberMovie", b =>
                {
                    b.Property<int>("CastId")
                        .HasColumnType("int");

                    b.Property<int>("StarredMoviesId")
                        .HasColumnType("int");

                    b.HasKey("CastId", "StarredMoviesId");

                    b.HasIndex("StarredMoviesId");

                    b.ToTable("CastMemberMovie");
                });

            modelBuilder.Entity("JAP_TASK_1_WEB_API.Models.CastMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CastMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Carrie Fisher"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mark Hamil"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Harrison Ford"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cole Sprouse"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lili Reinhart"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Camila Mendes"
                        },
                        new
                        {
                            Id = 7,
                            Name = "KJ Apa"
                        },
                        new
                        {
                            Id = 8,
                            Name = "James Spader"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Megan Boone"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Diego Klattenhoff"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Henry Lennix"
                        });
                });

            modelBuilder.Entity("JAP_TASK_1_WEB_API.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoverImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMovie")
                        .HasColumnType("bit");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverImage = "https://kbimages1-a.akamaihd.net/538b1473-6d45-47f4-b16e-32a0a6ba7f9a/1200/1200/False/star-wars-episode-iv-a-new-hope-3.jpg",
                            Description = "After Princess Leia, the leader of the Rebel Alliance, is held hostage by Darth Vader, Luke and Han Solo must free her and destroy the powerful weapon created by the Galactic Empire.",
                            IsMovie = true,
                            Rating = 5.0,
                            ReleaseDate = new DateTime(1997, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: A New Hope (Episode IV)"
                        },
                        new
                        {
                            Id = 2,
                            CoverImage = "https://images.penguinrandomhouse.com/cover/9780345320223",
                            Description = "Darth Vader is adamant about turning Luke Skywalker to the dark side. Master Yoda trains Luke to become a Jedi Knight while his friends try to fend off the Imperial fleet.",
                            IsMovie = true,
                            Rating = 4.7999999999999998,
                            ReleaseDate = new DateTime(1980, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: The Empire Strikes Back (Episode V)"
                        },
                        new
                        {
                            Id = 3,
                            CoverImage = "https://static.wikia.nocookie.net/riverdalearchie/images/3/3a/Season_2_Poster.jpg",
                            Description = "Archie, Betty, Jughead and Veronica tackle being teenagers in a town that is rife with sinister happenings and blood-thirsty criminals.",
                            IsMovie = false,
                            Rating = 4.5,
                            ReleaseDate = new DateTime(2017, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Riverdale"
                        },
                        new
                        {
                            Id = 4,
                            CoverImage = "https://static.wikia.nocookie.net/blacklist/images/5/57/Season_7_Poster.jpg",
                            Description = "A wanted fugitive mysteriously surrenders himself to the FBI and offers to help them capture deadly criminals. His sole condition is that he will work only with the new profiler, Elizabeth Keen.",
                            IsMovie = false,
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2013, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Blacklist"
                        });
                });

            modelBuilder.Entity("JAP_TASK_1_WEB_API.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RatedMovieId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RatedMovieId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RatedMovieId = 1,
                            Value = 5.0
                        },
                        new
                        {
                            Id = 2,
                            RatedMovieId = 2,
                            Value = 4.7999999999999998
                        },
                        new
                        {
                            Id = 3,
                            RatedMovieId = 3,
                            Value = 4.5
                        },
                        new
                        {
                            Id = 4,
                            RatedMovieId = 4,
                            Value = 5.0
                        });
                });

            modelBuilder.Entity("CastMemberMovie", b =>
                {
                    b.HasOne("JAP_TASK_1_WEB_API.Models.CastMember", null)
                        .WithMany()
                        .HasForeignKey("CastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JAP_TASK_1_WEB_API.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("StarredMoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JAP_TASK_1_WEB_API.Models.Rating", b =>
                {
                    b.HasOne("JAP_TASK_1_WEB_API.Models.Movie", "RatedMovie")
                        .WithMany("RatingList")
                        .HasForeignKey("RatedMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RatedMovie");
                });

            modelBuilder.Entity("JAP_TASK_1_WEB_API.Models.Movie", b =>
                {
                    b.Navigation("RatingList");
                });
#pragma warning restore 612, 618
        }
    }
}
